### ISSUE TITLE
Sounds path  problem and Chip Tester AutoWirer Bug in master branch

### ISSUE THREAD

**Issue by o51753007** [ThomasFooteDQ/DroidQuest#13]
Recently, when I was very excited to run this game, I notice the Sound didn't work.
So I watched the code, found this small wrong path  in Level.java
\src\com\droidquest\levels\Level.java
   ......
    public transient static String PICKUPSOUND = "pickup2.WAV";
    public transient static String DROPSOUND = "drop2.WAV";
    public transient static String BEEPSOUND = "beep2.WAV";
    public transient static String BUMPSOUND = "bump2.WAV";
    ......

Then I followed the tutorial to use Chip Tester AutoWirer function, it didn't Wiring the chip.
This time I don't know how to fix it. I think something missed in AutoWire.java file.

**Comment by FuzzyBoots** [comment]
AutoWire bug is fixed in https://github.com/ThomasFooteDQ/DroidQuest/pull/11

**Comment by o51753007** [comment]
Oh , I  saw that :P ,Thanks your Reply.
